### ISSUE TITLE
Szobacsinálós dolog

### ISSUE THREAD

**Issue by Elydra5** [FightMan01-bot/fightman01bot#123]
Nah Dr. Fájtmen és Dr. Tancsics lenne olyan ötletem mint pl a voice master bot, tudjon a fájtmen bot is ilyen voice szobát csinálni. Való igaz, ez nem egy eredeti ötlet, viszont mellé az eredetiség az lenne, hogy lehessen egy text szobát is csinálni, és pl törlődjön akkor, ha az adott ember aki létrehozta a szobát elment offline vagy nem ír bele senki már 5 perce vagy hogy az idő, hogy mennyi idő után törlődjön ha nem írnak bele állítható legyen.

**Comment by TancsicsGergely** [comment]
Pálinkásjóreggelt uram, majd elgondolkodunk az ötleten. Már szóba jött régebben ennek az ötlete, de elvetettük, mert nem volt megvalósáttal kapcsolatos ötletünk, illetve nem is volt nagyon kérve, meg értelmét sem láttuk. Ha szeretné az úr, megpróbálhatjuk, viszont mond meg, hogy melyik fontosabb/melyiket próbáljuk meg előbb.

**Comment by Elydra5** [comment]
Hétfőt az úrnak is. Nos én szerintem a voice szobás dolog teljesen megvalósítható lenne, már csak azért is, mivel vagy egy bot ami hasonlóképp funkcionál. Viszont hogy a fájtmen bot ilyen téren is egyedi legyen, úgy lehetne beállítani, hogy az adott szerver legnagyobb hangminőségét produkálja a bot, ergó a legnagyobb minőséggel készüljön a voice csatorna. Viszont a textre nagyobb igényt még nem látok, de lehet, hogy a ?!szobacsinalas lenne a leghasználtabb parancs (kekw). Szóval összegezve, szerintem először a voice csatornás megoldást lehetne megcsinálni, mert az még megvalósítható is, utánna pedig ha az urak ideje engedi, akkor a másiknak is nekiállhatnak. :szia_uram:

**Comment by TancsicsGergely** [comment]
Ma este lehet megpróbáljuk mert nagyon unatkozunk, később majd leírjuk h hol tartunk 😄
