### ISSUE TITLE
ChatCare

### ISSUE THREAD

**Issue by program2k20** [FightMan01-bot/fightman01bot#129]
**Hiba leírása**
Mikor hozzáakarok adni a ChatCare-hez egy csatornát, hogy azt ne vegye figyelembe akkor azt írja, hogy nincsen bekapcsolva a funkció miközben az bevan.

**Bővebb részletek**
Bekapcsoltam a chatcare-t, hozzáraktam az alapszavakat, beakartam neki adni egy szobát hogy azt ne evgye figyelembe a bot és ez után jött elő a hiba

**Minek kéne történnie?**
Hozzáadni az ignorált csatornákhoz az említett csatornát.

**Képernyőfotók**
https://program.fs.boltz.hu/mn116r.png

**Információk:**
 - OS: Windows 10 Pro 20H2 (Windows Insider béta csatorna)
 - Böngésző (ha arról használod a discordot) Alkalmazás
 - Discord app verzió (ha azt használod) Stable 64675 (92c9fdf)

**Comment by iamdoms** [comment]
Már fixálva, rakd újra be a ChatCare-t.
https://imgur.com/a/B2yDzqH

**Comment by program2k20** [comment]
Nem nagyon, ugyan az a hiba.
