### ISSUE TITLE
[KEZELŐFELÜLET] Görgetés, szépséghibák

### ISSUE THREAD

**Issue by shadowcoftheworld** [FightMan01-bot/fightman01bot#133]
**Hiba leírása**
Amikor módosítod a widgetek pozícióját, és utána jelölsz ki egy szervert, akkor az adatok a widgeteken kívül jelennek meg.

**Bővebb részletek**
Ezen kívül ha görgetsz, néhány widget a helyén marad görgetés alatt.

**Minek kéne történnie?**
A görgetésnél helyén maradnia, és az adatoknak a négyzeten belül maradnia

**Képernyőfotók**
![image](https://user-images.githubusercontent.com/51509676/90509818-39212080-e15a-11ea-9c93-a4953015eb72.png)

**Információk:**
Felesleges

**Comment by FightMan01** [comment]
Görgetésnél direkt, mert a görgetés egy bug.

A másikat sajnos nem tudom előidézni, esetleg egy videót dobj.

**Comment by FightMan01** [comment]
Egyébként nincs "Felesleges" infó, hányszor kell még hangsúlyozni.

**Comment by FightMan01** [comment]
Mert itt pl a böngésző lényeges lenne.

**Comment by TancsicsGergely** [comment]
Próbáljuk javítani, már van egy kis haladás, de még idő kell.

**Comment by SplitXPlayZ** [comment]
> 
> 
> Görgetésnél direkt, mert a görgetés egy bug.
> 
> A másikat sajnos nem tudom előidézni, esetleg egy videót dobj.

"görgetés egy bug."
100% false.

**Comment by TancsicsGergely** [comment]
Ah yes
Megjött az értelem képviselője

**Comment by SplitXPlayZ** [comment]
:roll_eyes:

**Comment by klmnblzs** [comment]
shut your sorry-ass up, asexual furry

**Comment by SplitXPlayZ** [comment]
"asexual furry"

**Comment by klmnblzs** [comment]
innit

**Comment by SplitXPlayZ** [comment]
system.core.error
