### ISSUE TITLE
Csatornakészítő

### ISSUE THREAD

**Issue by zarandthebende** [FightMan01-bot/fightman01bot#156]
**Ötlet részletei**
Jó lenne egy parancs, ami létrehoz egy hangcsatornát (pl. ?!createchannel). ?!setcategorie-val be lehet állítani azt, hogy milyen kategóriába csinálja a csatornát.
 Ha nem kerül kivalasztásra, akkor nem teszi kategóriába a csatornat. Ha az az ember, aki csinálta a csatornát, az kilép, akkor a csatorna törlődik
**Ezek voltak az ötlet részletei**

**Comment by Elydra5** [comment]
Lmao ezt már felvetettem
