### ISSUE TITLE
Anti raid rendszer kiegészítő funkció 

### ISSUE THREAD

**Issue by Elydra5** [FightMan01-bot/fightman01bot#157]
Mivel az elmúlt időben megnövekedett a raidek száma lehetne egy olyan funkció a botban hogy az ujjonnan kreált profilokat automatikusan kickeli csatlakozáskor

**Comment by Roli0109** [comment]
Vagy legalabb dobjon 1 értesítést

**Comment by TancsicsGergely** [comment]
Ki lett adva
