### ISSUE TITLE
Rang Becenév

### ISSUE THREAD

**Issue by kispintyi** [FightMan01-bot/fightman01bot#183]
**Hogyha a felhasználónak adunk rangot, és ahhoz a ranghoz 1 tetszőleges becenevet beállítottunk, akkor annak nevezze el a felhasználót. Több rangot is elnevezhetünk, de ilyenkor csak a legmagasabb rangnak a becenevét állítaná be a felhasználónak (abban az esetben ha több beceneves rang hozzá lett rendelve a felhasználóhoz).**

**Comment by TancsicsGergely** [comment]
Ki lett adva
