### ISSUE TITLE
Undo parancs

### ISSUE THREAD

**Issue by Ptoncsi** [FightMan01-bot/fightman01bot#198]
Minden moderátori műveletnek adni egy ID-t amit később az ID alapját vissza lehet keresni, és ban, mute stb esetén vissza lehet csinálni automatikus unbannal illetve invite küldéssel.

**Comment by SplitXPlayZ** [comment]
It can be possible, but it may have a lot of flaws. Bots cannot dm the user if that user isn't stayed on the server for a long period time, and it is random when the bot can dm the user.

**Comment by SplitXPlayZ** [comment]
Lehetséges, de sok hibája lehet. A botok nem tudják kezelni a felhasználót, ha az adott felhasználó nem marad hosszú ideig a szerveren, és véletlenszerű, hogy a bot képes-e a felhasználó felügyeletére.

**Comment by TancsicsGergely** [comment]
Nem lesz megvalósítva
