### ISSUE TITLE
PicNode API - Változás

### ISSUE THREAD

**Issue by vrolandd** [FightMan01-bot/fightman01bot#214]
Sziasztok!

Változott a PicNode API, Tancsics mondta hogy írjak ide, hogy ne felejtsétek el.
A változásokat a fightman-team csatornában PicNode DC szerveren látjátok, lusta voltam a GitHub-ot frissíteni xD

**Comment by TancsicsGergely** [comment]
WIP

**Comment by TancsicsGergely** [comment]
Fixelve
