### ISSUE TITLE
Xp kimutatása képpel a ?!level parancsnál

### ISSUE THREAD

**Issue by shadowcoftheworld** [FightMan01-bot/fightman01bot#216]
![Group 1 (5)](https://user-images.githubusercontent.com/51509676/102008089-41672200-3d2e-11eb-8ae3-0b3607c74c58.png)
![Group 2 (1)](https://user-images.githubusercontent.com/51509676/102008091-42984f00-3d2e-11eb-9976-f3c5ef1b82ae.png)

**Comment by TancsicsGergely** [comment]
👍
