### ISSUE TITLE
A https://fightman01bot.hu/ppads.php redesignja:

### ISSUE THREAD

**Issue by shadowcoftheworld** [FightMan01-bot/fightman01bot#218]
Jó napot uraim, csináltam néhány tervet a https://fightman01bot.hu/ppads.php oldalról, mert jelenleg eléggé szegényesen néz ki.

Képek:

![MacBook Pro - 4](https://user-images.githubusercontent.com/51509676/102693116-7edd1b00-4218-11eb-8048-f9e519e2e377.png)
![MacBook Pro - 3](https://user-images.githubusercontent.com/51509676/102693119-7f75b180-4218-11eb-8d0a-a01120afdbf9.png)
![MacBook Pro - 1](https://user-images.githubusercontent.com/51509676/102693120-800e4800-4218-11eb-9260-c8110bc20a39.png)
![MacBook Pro - 2](https://user-images.githubusercontent.com/51509676/102693121-800e4800-4218-11eb-8ef8-b0be0374bdae.png)

**Comment by 182marci** [comment]
A 2. képen lemaradt a nagy SIKER felirat, azt nézzétek el nekem

**Comment by TancsicsGergely** [comment]
> 
> 
> A 2. képen lemaradt a nagy SIKER felirat, azt nézzétek el nekem

Hát ez felháborító...

**Comment by 182marci** [comment]
> > A 2. képen lemaradt a nagy SIKER felirat, azt nézzétek el nekem
> 
> Hát ez felháborító...

:wkek:

**Comment by GamerTomii** [comment]
sexy

**Comment by iamdoms** [comment]
Jól látom, az ott egy AMD KENYÉRPIRÍTÓ A BAL ALSÓ SAROKBAN???

**Comment by shadowcoftheworld** [comment]
uhh mi?
