### ISSUE TITLE
Nyereményjáték és shop

### ISSUE THREAD

**Issue by XxkataxX** [FightMan01-bot/fightman01bot#232]
Már a 7.kódot kapom, de az is azt írja "sajnos nem nyertél semmit".

A szerverem shopjában nem lehet venni semmit mert azt írja hiba történt.A shopba vannak cuccok.

**Comment by petipeti156** [comment]
A kódok random vannak, van amikor ad pénzt, vagy semmit. A másikban nem tudok segíteni

**Comment by TancsicsGergely** [comment]
Ez a kódos dolog olyan, mint a lottó: vagy nyer, vagy nem, és arra, hogy nyerj, elég kicsi az esély. A boltos dologban pedig így nem tudok segíteni, discordon küldj egy meghívót privátban, és akkor rá tudok nézni.
