### ISSUE TITLE
Hibajelentés

### ISSUE THREAD

**Issue by Dokimin** [FightMan01-bot/fightman01bot#234]
***Ezek a pontok azért vannak, hogy a mi munkánkat is segítsek! NINCS OLYAN, HOGY VALAMELYIK FELESLEGES!!!***

**Hiba leírása**
A hiba az ,hogy 2 csatornát logol a bot. mod és a szervert ahova logol mindent a szerver, a mod log az nem irja ki hogy kitiltott valakit valaki . külön külön pl voice,felhasználó és az üzeneteket nem logolja külön külön se egybe.

**Bővebb részletek**
Külön nem logol a bot több csatornában.
**Minek kéne történnie?**
Ide írd, hogy szerinted minek kéne történnie.

**Képernyőfotók**
Ha lehet, képet csatolj!

**Információk:**
 - OS: [pl.: MacOS 10.15.4]
 - Böngésző (ha arról használod a discordot) [pl.: safari]
 - Discord app verzió (ha azt használod) [pl.: Canary 57889 (492e1b6)]

**Comment by Elydra5** [comment]
Most őszintén. EZ MÉGIS MI A FASZ?!

**Comment by Cyber28** [comment]
tehát.. nincsen logolás?

**Comment by TancsicsGergely** [comment]
Én megfejtettem a rejtjelezést!!!44!4!4!!!
Ezt írta le: az a baj, hogy a bot valahogyan (nincs is ilyen feature) nem egy, hanem több csatornába logol, viszont nem logol minden actiont (pl.: üzenetek törlése, felhasználó ki-be lépés)

**Comment by Elydra5** [comment]
> Én megfejtettem a rejtjelezést!!!44!4!4!!!
> Ezt írta le: az a baj, hogy a bot valahogyan (nincs is ilyen feature) nem egy, hanem több csatornába logol, viszont nem logol minden actiont (pl.: üzenetek törlése, felhasználó ki-be lépés)

Legyen akkor ilyen feature
