### ISSUE TITLE
Rank rendszer parancsfrissítés

### ISSUE THREAD

**Issue by Codyyboy** [FightMan01-bot/fightman01bot#236]
**Kérlek írd le az ötlet részleteit.**
Egy bő, jól érthető leírás az ötletedhez!

A rank/level rendszerben egy olyan parancs amivel betudom állítani, hogy hova küldje a szintlépéseket.
Meg belehessen állítani egy adott szinten, például ha eléri valaki a 20-as szintet kap egy rangod és az előzőt elveszi.

Remélem érthetően írtam le. Ha nem keressetek fel.

**Comment by iamdoms** [comment]
@TancsicsGergely ez done, nem?
