### ISSUE TITLE
Csatorna lock

### ISSUE THREAD

**Issue by Amaru8** [FightMan01-bot/fightman01bot#237]
**Kérlek írd le az ötlet részleteit.**
?!lock [idő]
Zárolja a csatornát. Ezáltal nem lehet majd bele írni. Ha megadsz egy időt, akkor visszaszámol, és ha letelik visszavonja és engedélyezi az üzeneteket. Ha nem, kikapcsolásig aktív lesz.

**Comment by Elydra5** [comment]
+1
