### ISSUE TITLE
Giveaway hiba..(?)

### ISSUE THREAD

**Issue by DavGP206** [FightMan01-bot/fightman01bot#240]
***Ezek a pontok azért vannak, hogy a mi munkánkat is segítsek! NINCS OLYAN, HOGY VALAMELYIK FELESLEGES!!!***

**Hiba leírása**
Egy rövid, de jól megfogalmazott leírás a hibáról.
A giveaway más országban más időt mutat.

**Bővebb részletek**
Lépések, hogy hogyan tudjuk a hibát előidézni.
Szóval. Csináltam egy szimpla nyereményjátékot és nekem azt mutatja, hogy most lesz vége. Én ugye Romániában élek. Aki meg magyarban él, annak azt mutatja, hogy 1 óra múlva. És így... ez nem a legjobb.

**Minek kéne történnie?**
Ide írd, hogy szerinted minek kéne történnie.
Minden országban ugyan azt kellene írja. 

**Képernyőfotók**
Ha lehet, képet csatolj!
nem szükséges. Csak egy órával kevesebbet mutat nálam. 

**Információk:**
 - OS: nem szükséges.
 - Böngésző: no
 - Discord app verzió: nem szükséges.

**Comment by FightMan01** [comment]
Idézem: "Ezek a pontok azért vannak, hogy a mi munkánkat is segítsek! NINCS OLYAN, HOGY VALAMELYIK FELESLEGES!!!"

Kérlek add meg a hiányzó információkat.

**Comment by DavGP206** [comment]
![Screenshot_20210206-153803_Chrome](https://user-images.githubusercontent.com/39192183/107119598-6d67d500-6891-11eb-8486-b49f2554dc38.png)
![Screenshot_20210206-153820_Discord](https://user-images.githubusercontent.com/39192183/107119602-722c8900-6891-11eb-8e9f-52ff1bbce923.png)
--------- Screenshotok.

OS: Android 10 *(de windowson is ugyan ez van.
)
Böngésző: Appot használok. De Chromeban nyitottam meg a weboodalt.
Discord app verzió: 59.12
