### ISSUE TITLE
Ellenorzo kod

### ISSUE THREAD

**Issue by Fate9** [FightMan01-bot/fightman01bot#247]
Esetleg meg lehetne csinalni hogy a kodot nem privatba kapja meg hanem abba a szobaba amit kivalasztunk a ?!ellsetup parancsal, ha esetleg olyan játékos csatlakozna fel a szerverre

**Comment by pi1255** [comment]
Szerintem jobb ahogy most van, mert így nem tudja más használni azt a kódot, ellehetetlenítve ezzel más hitelesítését
A DM messageben elküldött kód milliószor jobb, mintha a csatornába küldené

**Comment by iamdoms** [comment]
És mi lenne az üzenettel? ottmaradna? ha raidelik, törölgetheted ameddig akarod
