### ISSUE TITLE
Gban remove

### ISSUE THREAD

**Issue by pi1255** [FightMan01-bot/fightman01bot#252]
Ha valaki megkapja a gbant, esetleg lehetne, hogy mittomén, havonta felülvizsgálják, ha olyan indoka van, amely nem feltétlen veszélyezteti szervert.

**Comment by FightMan01** [comment]
Gbanra az esetek 99%-ban olyan kerülnek, akik veszélyesek lehetnek szerverekre, pont ez a dolog lényege. Egyébként akik a listán vannak, azoknak lehetőségük van fellebbezni, az ő dolguk, hogy élnek-e a lehetőséggel vagy sem. Rendesen alátámasztott érvekkel és normális indokokkal ha úgy ítéljük meg, levesszük a listáról.
