### ISSUE TITLE
Automoderátor

### ISSUE THREAD

**Issue by pi1255** [FightMan01-bot/fightman01bot#255]
Ha ?!getwarninfo-val lekérem egy warn részleteit, akkor, ha az automoderátor adta, akkor legyen benn, hogy mit törölt

**Comment by GamerTomii** [comment]
Akkor szerverhirdetésnél mutatná a linket 🤔

**Comment by pi1255** [comment]
azt mondjuk tényleg nem, de a többit szerintem mutathatja
