### ISSUE TITLE
EXPLODE

### ISSUE THREAD

**Issue by DarkBoy2005** [FightMan01-bot/fightman01bot#259]
Egy ?!explode parancs, amit ha lefuttatok xy csatornában, akkor törli azt a csatornát, majd létrehoz egy csatornát ugyan azokkal a beállításokkal

**Comment by pi1255** [comment]
Bocs, de pontosan mire gondolsz?
Lefuttatok egy parancsot, ami törli a csatornát majd csinál egy pontosan olyat?

Már bocs, de ennek mi értelme?
Ha egy kicsit kifejtenéd, lehet érteném, mire gondolsz.

**Comment by DarkBoy2005** [comment]
Pl szeretnél egy csatornát teljesen resetelni, de túl sok benne az üzenet, akkor ezzel könyebb, mint manuálisan

**Comment by pi1255** [comment]
Nem tom, szerintem a csatornákat nem szokás resetelni, legfeljebb a logot, de arra meg ott a ?!clear 100

**Comment by GamerTomii** [comment]
Ha az összes üzenetét szeretnéd törölni, akkor arra a Discordnak is van egy funkciója. Jobb kattolsz az adott csatornán, majd rányomsz a Clone channel-re.
Mellékesen a clear csak 2 hétnél fiatalabb üzeneteket tud törölni.
