### ISSUE TITLE
Hiba Jelentés.

### ISSUE THREAD

**Issue by Tempizet** [FightMan01-bot/fightman01bot#260]
Mostanság a Fightman01 bot fényéveket késik. Be jön egy tag és rá 2-3percre küldi ki a kódot és addigra ki is lép a tag csak ez a hiba miatt. Valamint a Log is késik még pedig legutóbb 4 percet késett.

**Comment by FightMan01** [comment]
A log esetén a késés érthető, mert a webhook tud úgynevezett rate limitet kapni, vagyis a discord addig nem engedi használni azt.
A kód küldésénél a 2-3 perc azért túlzás, főleg az, hogy mindig késik. Be kell vallani, hogy naponta meg van az a 30 perc, de ott is max 1-2 perc, de inkább 1.

**Comment by Tempizet** [comment]
És a kódon nem lehet javítani?

Németh Áron ***@***.***> ezt írta (időpont: 2021. márc. 27.,
Szo 23:38):

**Comment by FightMan01** [comment]
Kóddal semmi probléma nincs. Adatbázis optimalizálás a mai karbantartás alatt lesz.

**Comment by Tempizet** [comment]
Okés. Amúgy én arra a kódra gondoltam amit nekünk kiküld a verify hoz.

Németh Áron ***@***.***> ezt írta (időpont: 2021. márc. 28.,
V 12:02):
