### ISSUE TITLE
Youtube értesítő

### ISSUE THREAD

**Issue by Meszi84** [FightMan01-bot/fightman01bot#262]
Youtube értesítő.
Folyamatossan jelez hogy élő adás megy a csatornán. (Ami persze nem megy)
Ez a funkció már ki van kapcsolva.
![Screenshot_20210329-140452_Discord](https://user-images.githubusercontent.com/60156956/112834731-a0ac3080-9098-11eb-81a0-31405864069d.jpg)

**Comment by FightMan01** [comment]
Üdv! A csatorna linkjét el tudnád küldeni?
A rendszer egyébként a YouTube RSS "közvetítő" rendszerét használja, onnan kapja az adatokat. Illetve videókra ugyanúgy jelez.

**Comment by FightMan01** [comment]
De ha a {vidi} paramétert is használnád, akkor a linket is odarakná, így mindig tudnád, hogy mire jelez be.

**Comment by Meszi84** [comment]
1 csatorna volt felvéve csak. És így csatorna link lett meg adva. De nem igazán használtuk. Meg youtubra se rakunk fel mindig videot igy kivettük

**Comment by Meszi84** [comment]
https://youtube.com/channel/UCxpt_9cYNy4OSekxwBWeXew
