### ISSUE TITLE
Szabályzat elfogadása után csatornák mutatása

### ISSUE THREAD

**Issue by zarandthebende** [FightMan01-bot/fightman01bot#263]
**Az ötlet részletei**
Más botokban, pl. MEE6 van egy rendszer, amit ha beállítasz, akkor csak a szabályzat elfogadása után láthatod a csatornákat. Nem lenne rossz...

**Comment by Elydra5** [comment]
ellsetup vagy rangsetup

**Comment by FightMan01** [comment]
Ezt reakció ranggal is meg lehet oldani.

**Comment by zarandthebende** [comment]
jogos...
