### ISSUE TITLE
Role alapú warn kivétel

### ISSUE THREAD

**Issue by Elydra5** [FightMan01-bot/fightman01bot#264]
Role alapú warn kivétel bocs ezen nem tudok mit jobban taglalni, pl ?!removerolewarn @role ||ez elég egyértelmű||

**Comment by FightMan01** [comment]
Magyarul egy role bypass?

**Comment by Elydra5** [comment]
Olyasmi, de ez pl azért lenne jó mert ha egyszerre nagy számú ember kerül felvételre és elfelejtek nekik bypasst adni, és kapnak 10 warnt nem akarom egyesével torolni 20 embernél

**Comment by FightMan01** [comment]
1. Értem.
2. Van ember alapú warn törlés.

**Comment by Elydra5** [comment]
1.: oké xd
2.: ikr de egyszerűbb lenne sztem ha role alapján is el lehetne ezt érni. Vagy egyszerűen role bypass, hogy akinek van manage msgje akkor rögtön tesz rá bypasst
