### ISSUE TITLE
Képmanipuláció

### ISSUE THREAD

**Issue by DarkBoy2005** [FightMan01-bot/fightman01bot#268]
**Hiba leírása**
?!tweet parancskor, ha valakit megemlítesz az id-ját írja bele a tweetbe

**Bővebb részletek**
?!tweet és megemlítesz valakit

**Minek kéne történnie?**
Pl megemlítesz engem (!_𝘼𝙙𝙖𝙢ᴰᵉᵛ#0555) és ne a id szerinti említést másolja be, hanem azt, hogy "@!_𝘼𝙙𝙖𝙢ᴰᵉᵛ#0555"

**Képernyőfotók**
![kép](https://user-images.githubusercontent.com/68329594/113488961-a1422e00-94c1-11eb-9c81-89cf0224c94c.png)

**Információk:**
 - OS: [Windows 10]
 - Discord app verzió (ha azt használod) [pl.: Latest]

**Comment by FightMan01** [comment]
Javítva 👍
