### ISSUE TITLE
Gépigény

### ISSUE THREAD

**Issue by MiluGames7** [FightMan01-bot/fightman01bot#270]
Gépigény adatbázis bővítése

**Comment by FightMan01** [comment]
Üdv! Kérlek fejtsd ezt ki, pontosan milyen játékokat szeretnél bele?

**Comment by MiluGames7** [comment]
Például Geshin Impact, de olyan sok játék most nem jut eszembe.

Németh Áron ***@***.***> ezt írta (időpont: 2021. ápr. 9., P,
15:55):

**Comment by GamerTomii** [comment]
Valorant, Rocket League, Call of Duty, Cyberpunk 2077, Sea of Thieves, House Flipper, Among Us, Farming Simulator, OSU, League of Legends, Terraria, Phasmophobia, Doom Eternal, Counter Strike: Global Offensive, Outriders, Assasin's Creed, Red Dead Redemption 2, Euro Truck Simulator 2, Fifa 21, Rust, Far Cry 5, Hitman 3, The Sims 4, World of Tanks, World of Warships, World of Warcraft

puszi

**Comment by GOAT865** [comment]
ebből lesz még valami?
