### ISSUE TITLE
Szülinap beállítása szerverenként

### ISSUE THREAD

**Issue by zarandthebende** [FightMan01-bot/fightman01bot#272]
**Részletek**
Jó lenne egy parancs, ami be tudna állítani szülinapokat szerverenként
Pl: ?!birthday @Név YYYY/MM/DD

**Comment by who0-sys** [comment]
> **Részletek**
> Jó lenne egy parancs, ami be tudna állítani szülinapokat szerverenként
> Pl: ?!birthday @név YYYY/MM/DD

Ennek nincs sok értelme, hiszen a discord regisztrált születésnapokat nézi, bár úgysem adta meg senki az eredetit.
