### ISSUE TITLE
Antialt Hiba

### ISSUE THREAD

**Issue by dominik39293** [FightMan01-bot/fightman01bot#273]
Hiba a következő:
Nem tartja a bot a megadott "x" napot és beengedi a fiatalabb felhasználókat.
![unknown](https://user-images.githubusercontent.com/66879102/114583187-a2bde400-9c81-11eb-98e5-d93b704bf8bd.png)

**Comment by FightMan01** [comment]
Üdv! Mi a rendszert 1, 3 és 5 napos beállítással teszteltük, a DEV szerveren 3 napra van rakva, ott tökéletesen működik. Kérlek kapcsold ki a funkciót és kapcsold vissza 3 nappal, teszteld le, ha úgy megy és ezután sem menne 31 nappal, akkor kérlek írj újra.
