### ISSUE TITLE
Autonickall

### ISSUE THREAD

**Issue by Elydra5** [FightMan01-bot/fightman01bot#275]
Ha már van ?!autorole akkor lehetne ?!autonickall ami belépéskor akár role függően akár simán beallitana egy nevet az embereknek

**Comment by pi1255** [comment]
Van
?!autonick

**Comment by Elydra5** [comment]
Jogos, ez esetben rolenick autonick vagy hogy mondjam xd

**Comment by pi1255** [comment]
rolenick is van
?!rolenick

**Comment by Elydra5** [comment]
Wait, ha valakit átteszek abba a jogba amire be van állítva egy rolenick akkor annak is átállítja a nevét?

**Comment by pi1255** [comment]
Na látod, ezt már nem tudom

**Comment by Elydra5** [comment]
Nem állítja át. Szóval ez jó lenne xd mármint hogy role váltás során állítsa a nevét és ha már rajta van akkor is változtassa a nevét
