### ISSUE TITLE
ötlet

### ISSUE THREAD

**Issue by bacsi10** [FightMan01-bot/fightman01bot#278]
hello
szeretnék adni egy ötletet!
legyen egy ilyen command : ?!online/offline [ember] [csatorna] [online szöveg] [offline szöveg]                ez azt csinálná hogy az ember akit meg adsz az ha elérhető lesz vagy nem elérhető küld egy üzenetet a csatornába amit megadtál  és te valasztod ki hogy  amikor offline lesz mit irjon és ha online lesz mit írjon

**Comment by shadowcoftheworld** [comment]
Ez rate limitet válthatna ki a botból.

**Comment by bacsi10** [comment]
de ezt a code ot amit irtok hozzá ha megcsináljátok pls küldjétek el nekem  discordon python változatban pls pls ( dc nevem: .everyone#0359)

**Comment by shadowcoftheworld** [comment]
Ez nem így működik. A bot kódja privát, és privát is marad

**Comment by bacsi10** [comment]
pls
pls pls

**Comment by shadowcoftheworld** [comment]
Elmondtam, hogy ez nem így működik.

**Comment by bacsi10** [comment]
de annak a commandnak a scripjét

**Comment by bacsi10** [comment]
nem kell a boté

**Comment by shadowcoftheworld** [comment]
Ez a fightman01 bot repo, itt ötleteket, hibákat tudsz bejelenteni, de nem parancsok scriptjét kérni.

**Comment by shadowcoftheworld** [comment]
Nem ismétlem meg még egyszer.

**Comment by bacsi10** [comment]
_hát ötletet adok csak kell annak a commandnak a scritje_

**Comment by shadowcoftheworld** [comment]
De nem érted, hogy nem adjuk oda senkinek?

**Comment by bacsi10** [comment]
bocsi hogy kéregetek
