### ISSUE TITLE
[Ismert hiba] A bot üzenetet küldött sok embernek, miszerint behívták a botot egy szerverre.

### ISSUE THREAD

**Issue by iamdoms** [FightMan01-bot/fightman01bot#282]
Előfordulhat, hogy kaptatok a bottól privátban egy üzenetet, miszerint egy szerverre behívtátok, miközben ez nem így van. Valószínűleg discord problémáról beszélhetünk, mivel ez a része a botnak kb 1 éve nem is lett átírva. Elnézéseteket kérjük, amennyiben bármilyen kellemetlenséget okozott.

Support szerver: https://fightman01bot.hu/support

**Comment by FightMan01** [comment]
Azóta a probléma feledésbe került
