### ISSUE TITLE
egyszerre több warn

### ISSUE THREAD

**Issue by Elydra5** [FightMan01-bot/fightman01bot#284]
pl ?!warn {enber} {szám, ha kihagyod akk csak egyszer} {indok}
ennek kb annyi értelme lenne, hogyha valakit nem tudnak kitenni viszont a bot felette van, akk nem kell telespammelni x warnnal stb. na m1 nem értelmesen mondtam el, de ez egy faja dolog lenne sztem

**Comment by FightMan01** [comment]
Nem teljesen értem, szerintem elég 1 warn/parancs.
