### ISSUE TITLE
!Dashboard hiba! 

### ISSUE THREAD

**Issue by 0nyxx** [FightMan01-bot/fightman01bot#286]
Sziasztok, telefonon próbáltam belépni a bot dashboardjára, de nem lehet normálisan görgetni. Ha tudjátok javítsátok.
Üdv: 0nyx.

**Comment by shadowcoftheworld** [comment]
ikszdé

**Comment by iamdoms** [comment]
Szia, kérlek, ne kínozd magad azzal, hogy telefonon használod a dashboardot

**Comment by FightMan01** [comment]
A dashboard beta, nem telefon kompatibilis még.
