### ISSUE TITLE
Ticket

### ISSUE THREAD

**Issue by Elydra5** [FightMan01-bot/fightman01bot#291]
![2440EE87-334D-4480-83E9-CD69B47EE256](https://user-images.githubusercontent.com/66174724/117563455-41cdd400-b0a6-11eb-9196-81e52d6d190f.png)

Elvileg van tickete a gyereknek, és ezért nem tud nyitni, pedig végig néztem minden csatornát és sehol sem találtam egy ticketet sem tőle. A kategóriát megcsinálja a bot de ticketet nem bír nyitni

**Comment by FightMan01** [comment]
Lehet, hogy a csatorna kézzel lett törölve, majd ránézek a dologra.
