### ISSUE TITLE
Redesign.

### ISSUE THREAD

**Issue by shadowcoftheworld** [FightMan01-bot/fightman01bot#295]
A bot összes embedjének újra designolása kékre, nem pedig méreg színű zöldre.

**Comment by iamdoms** [comment]
350 parancs van, ebből kb 250 embedes. tudod ki fogja megcsinálni az összeset egyesével

**Comment by shadowcoftheworld** [comment]
Persze. Fightmanék

**Comment by TancsicsGergely** [comment]
igen xd

**Comment by shadowcoftheworld** [comment]
Mi igen?

**Comment by TancsicsGergely** [comment]
hát lehet megunom az életet és megcsinálom

**Comment by shadowcoftheworld** [comment]
Jó lenne...

**Comment by iamdoms** [comment]
ötlet: @TancsicsGergely kérek modit meg shadow is

**Comment by Elydra5** [comment]
> 350 parancs van, ebből kb 250 embedes. tudod ki fogja megcsinálni az összeset egyesével

Erre van a ctrl+f2

**Comment by FightMan01** [comment]
Szerintem a jelenlegi szín tökéletes
