### ISSUE TITLE
Auto moderátor

### ISSUE THREAD

**Issue by hexameter1** [FightMan01-bot/fightman01bot#297]
Van a botban az  auto moderátor hogy pl 5 warn után kick meg stb
és az az ötletem hogy lehetne olyan lehetőség ha az auto moderátor bannolja a tagot akkor privátban annak az embernek küld egy üzenetet hogy itt tud fellebbezni ha szerinte nem volt jogos.

**Comment by Elydra5** [comment]
+1

**Comment by FightMan01** [comment]
Szerintem elég ha ír egy Dm-et az adott szerver tulajának, a nevét beleírom az üzenetbe.
