### ISSUE TITLE
Védelem bot

### ISSUE THREAD

**Issue by satoko-official** [FightMan01-bot/fightman01bot#300]
**DoX Védelem**
Be lehetne állítani olyan neveket, amivel ha valaki csatlakozik azt automatikusan kibanolja. Továbbá lehetne olyan is hogy ha leír egy szót egyből banolja, és törölje az összes üzenetét.

**Comment by Elydra5** [comment]
Na és ezt hogy kepzelted el pontosabban?

**Comment by satokotheskid** [comment]
> Na és ezt hogy kepzelted el pontosabban?

?!nameblacklist be 
-> ?!nameblacklist add <név> | Ha pl: '?!nameblacklist add instagram' akkor ha valaki feljön a szerverre Instagram névvel, vagy I-n-s-t-a-g-r-a-m vagy hasonló alias névvel azt kibanolja a szerverről
A leíros dolog pedig lehetne a chatcare egyik funkciója, ahol bizonyos szavakért nem warn, hanem egyből ban járna
