### ISSUE TITLE
Új reaction role izéhez ötlet

### ISSUE THREAD

**Issue by Ptoncsi** [FightMan01-bot/fightman01bot#301]
**Kérlek írd le az ötlet részleteit.**
Ha setupolom az üzenetet és kétszer akarok hozzáadni egy rolet, akkor a mention után dobjon vissza, ne a leírás után, és ne dobjon ki teljesen csak vissza ahhoz a lépéshez, hogy "Fantasztikus! Kívánsz még gombot hozzáadni? (igen vagy nem)". (ha sok rolet akarok akkor idegesítő lehet mindig előlről kezdeni)

**Comment by FightMan01** [comment]
Javítva.
