### ISSUE TITLE
(szerintem) crashel a reaction role folyamat

### ISSUE THREAD

**Issue by Ptoncsi** [FightMan01-bot/fightman01bot#302]
***Ezek a pontok azért vannak, hogy a mi munkánkat is segítsek! NINCS OLYAN, HOGY VALAMELYIK FELESLEGES!!!***

**Hiba leírása**
Ha sok karaktert (én 2000-t teszteltem) adok meg a gomb szövegének akkor nem kapok semmi választ.

**Bővebb részletek**
Elkezdek egy setupot
beállítok mindent de gomb szövegnek 2000 karakteres szöveget adok meg

**Minek kéne történnie?**
Visszaírnia a botnak hogy "túl hosszú szöveg" vagy valami hasonló
**Képernyőfotók**
![kép_2021-06-01_120107](https://user-images.githubusercontent.com/67435560/120305449-0c955a00-c2d1-11eb-882c-b378c6f25bd1.png)
![kép_2021-06-01_120144](https://user-images.githubusercontent.com/67435560/120305538-22a31a80-c2d1-11eb-8be9-c819c4c5a906.png)

**Információk:**
bot hiba, szerintem ez ide nem fontos

**Comment by FightMan01** [comment]
Igen, írtam is devre ezzel kapcsolatban. Eddig ismeretlen info volt, most már tudom: maximum 80 karakter lehet a gomb szövege.

**Comment by FightMan01** [comment]
Egyébként a hibát éppen pár perce javítottam.
