### ISSUE TITLE
Több funkció a számológépbe

### ISSUE THREAD

**Issue by Ptoncsi** [FightMan01-bot/fightman01bot#304]
**Kérlek írd le az ötlet részleteit.**
(ez nem egészen a címhez kapcsolódik, de ha megoldható akkor a piros gombok is lehetnének ugyan olyan hosszúak)

Lehetnének lapozás/ugrás gombok, és ha megnyomom akkor a művelet és szám gombok is átváltoznak komplikáltabb műveletekre, mint pl a Win10 számológép, csak kevesebb füllel.

**Comment by FightMan01** [comment]
Jelenleg marad a basic, ennyi szerintem mindenkinek elég. Ha valaki komplikáltabb műveletekre vágyik, az valószínű nem ezt fogja eleve használni.
