### ISSUE TITLE
Amőba hiba

### ISSUE THREAD

**Issue by Elydra5** [FightMan01-bot/fightman01bot#306]
Máté jött, reagált rá, de én is ranyomtam, és nekem adta be, így megnyertem ||remélem érthetően irtam le de este van és nem tudok fogalmazni, a kép beszél magáért||
![4FEBE7B8-778B-4A13-94C5-14AF532C5148](https://user-images.githubusercontent.com/66174724/120864097-f8c94c80-c58b-11eb-9f7a-0a1045f9c9fe.jpeg)

**Comment by FightMan01** [comment]
Azóta javítva lett.
