### ISSUE TITLE
unbanall átdolgozása

### ISSUE THREAD

**Issue by Elydra5** [FightMan01-bot/fightman01bot#307]
![image](https://user-images.githubusercontent.com/66174724/120893242-89e30680-c612-11eb-9db9-7c01942f9449.png)
kérdezzen rá a bot, hogy biztos meg akarom e tenni

**Comment by FightMan01** [comment]
Szerintem ez felesleges, mivel a parancs nevéből egyértelműen kiderül a célja, szerintem ha valaki ezt beírja akkor tudja, hogy ki fog történni.
