### ISSUE TITLE
?!rolebypass hiba

### ISSUE THREAD

**Issue by pi1255** [FightMan01-bot/fightman01bot#316]
***Ezek a pontok azért vannak, hogy a mi munkánkat is segítsek! NINCS OLYAN, HOGY VALAMELYIK FELESLEGES!!!***

**Hiba leírása**
a rolebypass nem ír heles használatot

**Bővebb részletek**
beírom, hogy ?!rolebypass és nem történik semmi

**Minek kéne történnie?**
Kiírja a helyes használatot

**Comment by FightMan01** [comment]
Javítva.
