### ISSUE TITLE
?!gbanreport hiba

### ISSUE THREAD

**Issue by pi1255** [FightMan01-bot/fightman01bot#317]
***Ezek a pontok azért vannak, hogy a mi munkánkat is segítsek! NINCS OLYAN, HOGY VALAMELYIK FELESLEGES!!!***

**Hiba leírása**
A gbanreport mikor nem adok meg egy argot se, ugye kiírja a helyes használatot. Viszont ott írja, ha csak név#szám formátumban tudom az illető elérhetőségét, akkor használjam a ?!userfind parancsot 
De mivel egy updateben át lett írva, hogy a userfind csak id alapján megy, ez itt nem jó

Áron kérlek, ezzel csinálj valamit, vagy a message legyen más, vagy a userfind működjön újra náv#szám formátummal is

**Comment by FightMan01** [comment]
Valóban nem lett átírva, de attól még ott a ?!useridfind parancs.
