### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by pi1255** [FightMan01-bot/fightman01bot#322]
**Kérlek írd le az ötlet részleteit.**
Egy bő, jól érthető leírás az ötletedhez!

A Dashboardon a szerverválasztóban ne csak azok közül a szerverek közül választhassunk, ahol adminjogunk van, hanem ahol a bot és én is bent vagyok.

Csak ott ne legyen jogom a beállításokat módosítani, csak megnézni, meg esetleg onnan is meg lehetne nézni az adott serveren lévő warnjaimat, satöbbit.

**Comment by FightMan01** [comment]
Egyelőre marad az az elv, hogy ahol jogod van. Többség egyébként így kérte
