### ISSUE TITLE
banlist

### ISSUE THREAD

**Issue by Elydra5** [FightMan01-bot/fightman01bot#330]
nahyo áron sztem félre értetted amit sokan kértek, ez a banlist így jelen helyzetben katasztrofális. mint pl az fm01 szerónál 127 kitiltott tag mellett rohadtul nem akarod egyesével végig nyomogatni a kis nyilacskát, hogy elérj oda ahova akarsz. lehet hogy van beépített banlist de ha valami nokika nem tudja használni sokkal egyszerűbb ezzel, ezért csináld meg kedves uram úgy, hogy egy oldalon mutasson max 15 darabot, és ha lehet gombokkal lehessen váltogatni mert az kva fasza, vagy ha ilyen megoldás marad, akkor úgy legyen megcsinálva, hogy csak az az user lássa, aki le is kérte a parancsot aztán majd gombokkal lehessen váltogatni az oldalakat

**Comment by TancsicsGergely** [comment]
van erre már egy még jobb ötletünk ami work in progress, nemsokára kész lesz, és szerintünk az lesz a legjobb amit ki tudunk ebből a banlist dologból hozni

**Comment by Elydra5** [comment]
bármit csak ne a mostanit
