### ISSUE TITLE
?!roleinfo update

### ISSUE THREAD

**Issue by pi1255** [FightMan01-bot/fightman01bot#331]
Áron esetleg, ha van időd, megcsinálhatnád, hogy 
A roleinfo parancsnál a jogosultságokat ne csak számként, hanem perm hierarchy szerint, csökkenő sorrendben is írja ki.
Administrátor, Szerver kezelése, stb...

Mert ha a rang jogait akarom megtudni, akkor a számokból nem sokat értek

**Comment by FightMan01** [comment]
Kész
