### ISSUE TITLE
Új system

### ISSUE THREAD

**Issue by DarkBoy2005** [FightMan01-bot/fightman01bot#344]
Aki ismeri a Wick botot az tudhatja, hogy miről beszélek, aki pedig nem az majd megnézi
A Wick botban van egy nagyon jó és egyszerű rendszer, ami elnyerte a tetszésem, mégpedig ez a heat system. Gyakorlatilag van minden egyes felhasználónak egy százalék mérője, ami ha eléri a 100%-ot akkor büntetést kap a beállítottak szerint.
Pl: Valaki káromkodik 1x akkor a heat-hez hozzá lesz adva 40% és addig káromkodhat, míg ez 100% nem lesz. Ez ugyan így mehetne szerver meghívók, spam meg mindenhez és akkor egy nagyon király kis rendszert lehetne össze dobni.

**Comment by FightMan01** [comment]
Ötletes rendszer, viszont nem szeretnénk ilyen értelemben lemásolni, hadd maradjon ez meg nekik, a mi rendszerünk is hasonlóan működik abból a szempontból, hogy egy bizonyos pontig kapsz figyelmeztetést és utánna "bírságot", viszont ez a cooldown dolog nem is rossz ötlet

**Comment by FightMan01** [comment]
(Gergely írta csak az én fiókomba volt belépve)
