### ISSUE TITLE
Name history

### ISSUE THREAD

**Issue by shadowcoftheworld** [FightMan01-bot/fightman01bot#356]
?!namehistory @név

Lehetőség a felhasználó régebbi neveinek megtekintésére.

**Comment by FightMan01** [comment]
Ezt az ötletet félreraknám. Nem tudom mennyire jó ötlet a felhasználók adatait ilyen szinten tárolni.

**Comment by Peti1** [comment]
logger bot is tárolja, ott ki lehet törölni 1 paranccsal az összes adatot magaról mint pl ezt

**Comment by FightMan01** [comment]
Szerintem majd megszavaztatom, aztán meglátjuk, addig marad ez elhalasztva státuszban.
