### ISSUE TITLE
Jó lenne ha lehetne konvertálni a bottal is

### ISSUE THREAD

**Issue by simrol** [FightMan01-bot/fightman01bot#358]
Sokat szoktam videót vágni,és mellé tartozik a konvertálás is.
Tudok nyílvános API-t is.
https://cloudconvert.com/api/v2

**Comment by FightMan01** [comment]
Úgy gondolom, hogy ha valaki egy fájlt szeretne konvertálni, azt egyszerűbben megteheti ha felmegy valamilyen oldalra. Nem beszélve arról, hogy nitro nélkül maximum 8MB-ot lehet feltölteni. És ez a botokra is ugyanúgy vonatkozik.
