### ISSUE TITLE
Reddit helyett pornhub api az NSFW parancsnak

### ISSUE THREAD

**Issue by SKW7** [FightMan01-bot/fightman01bot#361]
Akárhányszor használom a ?!nsfw parancsot, valamiért nem olyan képeket dob be, amire számítok XD
Remélem nem ad terhet az, hogy ki kell cserélni az api-t redditről pornhub-ra :|

**Comment by Peti1** [comment]
menj fel phra azt nézzed

**Comment by FightMan01** [comment]
Nem tervezem a cserét.
