### ISSUE TITLE
helyesírásellenőrzés

### ISSUE THREAD

**Issue by 250racing** [FightMan01-bot/fightman01bot#362]
Beirsz a chatba valamilyen parancsot mögé a szót, és leirja helyesen

btw Nem nekem kell xd

**Comment by Elydra5** [comment]
Tanulj meg helyesen írni. Problem solved.

**Comment by FightMan01** [comment]
Nem tervezek ilyet, rengeteg weboldal van erre és szerintem túl sok értelme sincs.

**Comment by GoatWasTaken** [comment]
https://helyesiras.mta.hu/helyesiras/default/suggest helo
