### ISSUE TITLE
Invitelogger

### ISSUE THREAD

**Issue by 250racing** [FightMan01-bot/fightman01bot#364]
Egy InviteLogger a bothoz.

Egy olyan, ami számolja a meghívását, ki hívta meg, mikor ment az invite (ha ezt lehet logolni), mikor lépett be. 

És attol függöen, hogy hány meghívása van a tagnak, vagy privált üzenetet vagy rangot adjon a tagnak. 

(remélem nincs benne a botban :D)

**Comment by FightMan01** [comment]
Régebben volt ilyen, ám teljesítményproblémákat okozott, illetve a discord maga sem szereti ezt annyira (tekintve hogy könnyen lehet rate limitet kapni invite loggerrel)
