### ISSUE TITLE
Az ötletem 

### ISSUE THREAD

**Issue by DaBigDYT** [FightMan01-bot/fightman01bot#375]
Sziasztok! Az ötletem az, hogy amikor kirak xy egy videót vagy sztorit tiktora akkor jelezzen a bot egy állítható üzenettel xy csatornába. Jó lenne hogyha ugyan ez lenne a youtube-al is. Köszi előre is, és remélem hogy minden jól megy a kódólásban és ez a nagy kérés bele kezül a bot hosszú programai közé. Ismét köszönöm

**Comment by shadowcoftheworld** [comment]
Szia, ez már létezik. Erre van a ?!setytannounce és a ?!settwannounce
