### ISSUE TITLE
név ötlet

### ISSUE THREAD

**Issue by LittleMC** [FightMan01-bot/fightman01bot#386]
**Kérlek írd le az ötlet részleteit.**
Egy bő, jól érthető leírás az ötletedhez!
nevezzétek átt a fightmanbotot arra hogy fingmanbot

**Comment by Peti1** [comment]
u must be the funniest in your class 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂
