### ISSUE TITLE
szar

### ISSUE THREAD

**Issue by LittleMC** [FightMan01-bot/fightman01bot#387]
***Ezek a pontok azért vannak, hogy a mi munkánkat is segítsek! NINCS OLYAN, HOGY VALAMELYIK FELESLEGES!!!***

**Hiba leírása**
Egy rövid, de jól megfogalmazott leírás a hibáról.

**Bővebb részletek**
Lépések, hogy hogyan tudjuk a hibát előidézni.

**Minek kéne történnie?**
Ide írd, hogy szerinted minek kéne történnie.

**Képernyőfotók**
Ha lehet, képet csatolj!

**Információk:**
 - OS: [pl.: MacOS 10.15.4]
 - Böngésző (ha arról használod a discordot) [pl.: safari]
 - Discord app verzió (ha azt használod) [pl.: Canary 57889 (492e1b6)]
szar

**Comment by LittleMC** [comment]
szar

**Comment by GOAT865** [comment]
szegény gyereknek nincs mit csinálni amíg apu és anyu nincs otthon :(
