### ISSUE TITLE
Új discordon

### ISSUE THREAD

**Issue by Godrogi** [FightMan01-bot/fightman01bot#388]
Jó napot. Az én Fiókom nem mult el 7 napos. És a bot Kirúg vagy bannol?

A Választ előre köszönöm

**Comment by TancsicsGergely** [comment]
Van ilyen beállítás, szervertől függ
Ha nem elég idős a profilod, akkor kidob a szerverről

**Comment by Godrogi** [comment]
Szóval nem bannol?

**Comment by Godrogi** [comment]
És köszönöm

**Comment by TancsicsGergely** [comment]
nem

**Comment by Godrogi** [comment]
Köszönöm
