### ISSUE TITLE
CUSTOM COMMANDS

### ISSUE THREAD

**Issue by Roli0109** [FightMan01-bot/fightman01bot#43]
Hasonlót mint a mee6-nál 
(csak jobbat)

Ha ez megtörténik abban az esetben megválnék azonnal a mee6-tól

**Comment by TancsicsGergely** [comment]
Már terveztük, hogy az új dashboardon legyen erre lehetőség, majd meglátjuk, hogy hogyan sikerül :D

**Comment by iamdoms** [comment]
@TancsicsGergely már van, milyen lenne egy close

**Comment by TancsicsGergely** [comment]
tényleg? mióta?
