### ISSUE TITLE
ARK Szerver Státusz Kiírás

### ISSUE THREAD

**Issue by Elydra5** [FightMan01-bot/fightman01bot#90]
**Üdv az uraknak!**
Az új ötletem annyi lenne (már ha ez megvalósítható), hogy egy adott ARK szerver állapotát lehessen megnézni. Pl ?!serverstat {ip} és kiadja hogy mennyien vannak rajta, elérhető e stb stb. Erre API-t vagy hasonlókat szerintem már tudnátok találni. 
Btw csak így tovább :GWugyvanparasztigazadvan:

**Comment by FightMan01** [comment]
🤔:ugyvanparasztigazadvan:

**Comment by FightMan01** [comment]
Tudsz dobni egy IP-t példának?

**Comment by Elydra5** [comment]
hinnye verte meg így nem tudok, de gyors keresek egyet

**Comment by FightMan01** [comment]
:vertemeg:
